import { ArrowLeft, Printer } from "lucide-react";
import { EmptyState, ProgressBar, StatusBadge } from "./ui.jsx";
import { GanttChart } from "./GanttChart.jsx";
import { formatShortDate } from "../utils/dateUtils.js";
import geoBrandLogo from "../assets/brand/geotech3d-logo-full.svg";

export function ProjectGanttReport({ project, tasks, employees, currentUser, onPrint, onBack }) {
  if (!project) {
    return <EmptyState title="No project selected" text="Open a project, then generate its Gantt report." />;
  }

  const dateLabel = new Date().toLocaleDateString("en-GB", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const manager = employees.find((employee) => employee.id === project.managerId);
  const team = employees.filter((employee) => (project.team || []).includes(employee.id));
  const sortedTasks = [...tasks].sort((a, b) => String(a.start).localeCompare(String(b.start)));

  return (
    <div className="stack project-gantt-report">
      <div className="report-actions-bar no-print">
        <button className="secondary-button" type="button" onClick={onBack}>
          <ArrowLeft size={16} aria-hidden="true" />
          Back
        </button>
        <button className="report-cta" type="button" onClick={onPrint}>
          <Printer size={16} aria-hidden="true" />
          Print / Save as PDF
        </button>
      </div>

      <section className="panel report-sheet">
        <header className="report-header">
          <img src={geoBrandLogo} alt="GEOTECH 3D - Geospatial Hub" className="report-logo" />
          <div className="report-heading">
            <span className="eyebrow">Project Gantt &amp; Schedule Report</span>
            <h2>{project.name}</h2>
            <p>{project.id} · {dateLabel}</p>
          </div>
        </header>

        <div className="report-plan-grid">
          <div><span>Client</span><strong>{project.client || "—"}</strong></div>
          <div><span>Manager</span><strong>{manager?.name || "Unassigned"}</strong></div>
          <div><span>Status</span><strong>{project.status}</strong></div>
          <div><span>Team Size</span><strong>{team.length}</strong></div>
          <div><span>Start (Receipt)</span><strong>{formatShortDate(project.start)}</strong></div>
          <div><span>Due (Delivery)</span><strong>{formatShortDate(project.end)}</strong></div>
          <div><span>Tasks</span><strong>{tasks.length}</strong></div>
          <div><span>Progress</span><strong>{Number(project.progress || 0)}%</strong></div>
        </div>

        <div className="report-section-title">
          <h3>Project Plan Timeline (Gantt)</h3>
        </div>
        <GanttChart tasks={tasks} projects={[project]} employees={employees} />

        <div className="report-section-title">
          <h3>Schedule &amp; Delivery Dates</h3>
        </div>
        {sortedTasks.length ? (
          <table className="report-table">
            <thead>
              <tr>
                <th>Task</th>
                <th>Assignee</th>
                <th>Status</th>
                <th>Progress</th>
                <th>Start (Receipt)</th>
                <th>Due (Delivery)</th>
              </tr>
            </thead>
            <tbody>
              {sortedTasks.map((task) => {
                const assignee = employees.find((employee) => employee.id === task.assigneeId);
                return (
                  <tr key={task.id}>
                    <td><strong>{task.title}</strong></td>
                    <td>{assignee?.name || "Unassigned"}</td>
                    <td><StatusBadge value={task.status} /></td>
                    <td>{Number(task.progress || 0)}%</td>
                    <td>{formatShortDate(task.start)}</td>
                    <td>{formatShortDate(task.end)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        ) : (
          <p className="report-empty-note">No scheduled tasks for this project yet.</p>
        )}

        <div className="report-footer">
          Generated by {currentUser?.name || "GEOTECH 3D"} · GEOTECH 3D Geospatial Hub
        </div>
      </section>
    </div>
  );
}
